#!/usr/bin/env bash

default="$HOME"

pid=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.type=="con") | select(.focused==true).pid')
ppid=$(pgrep --newest --parent ${pid})
path=$(readlink /proc/${ppid}/cwd || echo "$default")

if test -d "$path"; then
	echo "$path"
else
	echo "$default"
fi
