alias dg='git --git-dir "$HOME/.dotfiles" --work-tree "$HOME"'
abbr dga 'dg add -f'
abbr dgam 'dg commit -am'
abbr dgc 'dg commit -p --verbose'
abbr dgd 'dg diff'
abbr dgdl 'dg diff HEAD~1 HEAD'
abbr dgds 'dg diff --staged'
abbr dgl 'dg pull --autostash'
abbr dglo 'dg log --oneline'
abbr dgp 'dg push'
abbr dgr 'dg rebase -i HEAD~5'
abbr dgs 'dg status -s'
